#!/bin/sh

set -e

case "$1" in
  configure)
        chown -R root:openio /usr/share/oio-netdata /usr/lib/oio-netdata /usr/lib/x86_64-linux-gnu/oio-netdata
        chown -R root:openio /var/lib/oio-netdata /var/cache/oio-netdata /var/log/oio-netdata
        chmod -R g+w /var/lib/oio-netdata /var/cache/oio-netdata /var/log/oio-netdata

        setcap cap_dac_read_search,cap_sys_ptrace+ep /usr/lib/x86_64-linux-gnu/oio-netdata/plugins.d/apps.plugin
        chmod 0550 /usr/lib/x86_64-linux-gnu/oio-netdata/plugins.d/apps.plugin
        chown root:openio /usr/lib/x86_64-linux-gnu/oio-netdata/plugins.d/apps.plugin

        setcap cap_sys_resource,cap_sys_admin+ep /usr/lib/x86_64-linux-gnu/oio-netdata/plugins.d/ebpf_process.plugin
        chmod 4550 /usr/lib/x86_64-linux-gnu/oio-netdata/plugins.d/ebpf_process.plugin
        chown root:openio /usr/lib/x86_64-linux-gnu/oio-netdata/plugins.d/ebpf_process.plugin
        ;;
esac
exit 0
