Document: oiofs-fuse
Title: Debian oiofs-fuse Manual
Author: <insert document author here>
Abstract: This manual describes what oiofs-fuse is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/oiofs-fuse/oiofs-fuse.sgml.gz

Format: postscript
Files: /usr/share/doc/oiofs-fuse/oiofs-fuse.ps.gz

Format: text
Files: /usr/share/doc/oiofs-fuse/oiofs-fuse.text.gz

Format: HTML
Index: /usr/share/doc/oiofs-fuse/html/index.html
Files: /usr/share/doc/oiofs-fuse/html/*.html
