Document: openio-sds-swift-extended
Title: Debian openio-sds-swift-extended Manual
Author: <insert document author here>
Abstract: This manual describes what openio-sds-swift-extended is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/openio-sds-swift-extended/openio-sds-swift-extended.sgml.gz

Format: postscript
Files: /usr/share/doc/openio-sds-swift-extended/openio-sds-swift-extended.ps.gz

Format: text
Files: /usr/share/doc/openio-sds-swift-extended/openio-sds-swift-extended.text.gz

Format: HTML
Index: /usr/share/doc/openio-sds-swift-extended/html/index.html
Files: /usr/share/doc/openio-sds-swift-extended/html/*.html
