Document: openio-sds
Title: Debian openio-sds Manual
Author: <insert document author here>
Abstract: This manual describes what openio-sds is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/openio-sds/openio-sds.sgml.gz

Format: postscript
Files: /usr/share/doc/openio-sds/openio-sds.ps.gz

Format: text
Files: /usr/share/doc/openio-sds/openio-sds.text.gz

Format: HTML
Index: /usr/share/doc/openio-sds/html/index.html
Files: /usr/share/doc/openio-sds/html/*.html
