Document: openio-shinken-import
Title: Debian openio-shinken-import Manual
Author: <insert document author here>
Abstract: This manual describes what openio-shinken-import is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/openio-shinken-import/openio-shinken-import.sgml.gz

Format: postscript
Files: /usr/share/doc/openio-shinken-import/openio-shinken-import.ps.gz

Format: text
Files: /usr/share/doc/openio-shinken-import/openio-shinken-import.text.gz

Format: HTML
Index: /usr/share/doc/openio-shinken-import/html/index.html
Files: /usr/share/doc/openio-shinken-import/html/*.html
