#!/bin/sh
set -efu

pys="$(py3versions -r 2>/dev/null)"

cd "$ADTTMP"

for py in $pys; do
	echo "=== $py ==="
	LC_ALL=C.UTF-8 xvfb-run --auto-servernum --server-args="-screen 0 1024x768x24" $py /usr/bin/nosetests3 -a '!network' -v pandas 2>&1
done
