Document: openio-sds-rsyslog
Title: Debian openio-sds-rsyslog Manual
Author: <insert document author here>
Abstract: This manual describes what openio-sds-rsyslog is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/openio-sds-rsyslog/openio-sds-rsyslog.sgml.gz

Format: postscript
Files: /usr/share/doc/openio-sds-rsyslog/openio-sds-rsyslog.ps.gz

Format: text
Files: /usr/share/doc/openio-sds-rsyslog/openio-sds-rsyslog.text.gz

Format: HTML
Index: /usr/share/doc/openio-sds-rsyslog/html/index.html
Files: /usr/share/doc/openio-sds-rsyslog/html/*.html
