Document: python-django-redis-cache
Title: Debian python-django-redis-cache Manual
Author: <insert document author here>
Abstract: This manual describes what python-django-redis-cache is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/python-django-redis-cache/python-django-redis-cache.sgml.gz

Format: postscript
Files: /usr/share/doc/python-django-redis-cache/python-django-redis-cache.ps.gz

Format: text
Files: /usr/share/doc/python-django-redis-cache/python-django-redis-cache.text.gz

Format: HTML
Index: /usr/share/doc/python-django-redis-cache/html/index.html
Files: /usr/share/doc/python-django-redis-cache/html/*.html
