Document: openio-sds-logrotate
Title: Debian openio-sds-logrotate Manual
Author: <insert document author here>
Abstract: This manual describes what openio-sds-logrotate is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/openio-sds-logrotate/openio-sds-logrotate.sgml.gz

Format: postscript
Files: /usr/share/doc/openio-sds-logrotate/openio-sds-logrotate.ps.gz

Format: text
Files: /usr/share/doc/openio-sds-logrotate/openio-sds-logrotate.text.gz

Format: HTML
Index: /usr/share/doc/openio-sds-logrotate/html/index.html
Files: /usr/share/doc/openio-sds-logrotate/html/*.html
