Document: python-plyvel
Title: Debian python-plyvel Manual
Author: <insert document author here>
Abstract: This manual describes what python-plyvel is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/python-plyvel/python-plyvel.sgml.gz

Format: postscript
Files: /usr/share/doc/python-plyvel/python-plyvel.ps.gz

Format: text
Files: /usr/share/doc/python-plyvel/python-plyvel.text.gz

Format: HTML
Index: /usr/share/doc/python-plyvel/html/index.html
Files: /usr/share/doc/python-plyvel/html/*.html
