Document: openio-sds-swift
Title: Debian openio-sds-swift Manual
Author: <insert document author here>
Abstract: This manual describes what openio-sds-swift is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/openio-sds-swift/openio-sds-swift.sgml.gz

Format: postscript
Files: /usr/share/doc/openio-sds-swift/openio-sds-swift.ps.gz

Format: text
Files: /usr/share/doc/openio-sds-swift/openio-sds-swift.text.gz

Format: HTML
Index: /usr/share/doc/openio-sds-swift/html/index.html
Files: /usr/share/doc/openio-sds-swift/html/*.html
