Document: puppet-module-openio-openiosds
Title: Debian puppet-module-openio-openiosds Manual
Author: <insert document author here>
Abstract: This manual describes what puppet-module-openio-openiosds is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/puppet-module-openio-openiosds/puppet-module-openio-openiosds.sgml.gz

Format: postscript
Files: /usr/share/doc/puppet-module-openio-openiosds/puppet-module-openio-openiosds.ps.gz

Format: text
Files: /usr/share/doc/puppet-module-openio-openiosds/puppet-module-openio-openiosds.text.gz

Format: HTML
Index: /usr/share/doc/puppet-module-openio-openiosds/html/index.html
Files: /usr/share/doc/puppet-module-openio-openiosds/html/*.html
