Document: openio-dashboard-frontend
Title: Debian openio-dashboard-frontend Manual
Author: <insert document author here>
Abstract: This manual describes what openio-dashboard-frontend is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/openio-dashboard-frontend/openio-dashboard-frontend.sgml.gz

Format: postscript
Files: /usr/share/doc/openio-dashboard-frontend/openio-dashboard-frontend.ps.gz

Format: text
Files: /usr/share/doc/openio-dashboard-frontend/openio-dashboard-frontend.text.gz

Format: HTML
Index: /usr/share/doc/openio-dashboard-frontend/html/index.html
Files: /usr/share/doc/openio-dashboard-frontend/html/*.html
