Document: python-engineio
Title: Debian python-engineio Manual
Author: <insert document author here>
Abstract: This manual describes what python-engineio is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/python-engineio/python-engineio.sgml.gz

Format: postscript
Files: /usr/share/doc/python-engineio/python-engineio.ps.gz

Format: text
Files: /usr/share/doc/python-engineio/python-engineio.text.gz

Format: HTML
Index: /usr/share/doc/python-engineio/html/index.html
Files: /usr/share/doc/python-engineio/html/*.html
