Document: diamond-openio
Title: Debian diamond-openio Manual
Author: <insert document author here>
Abstract: This manual describes what diamond-openio is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/diamond-openio/diamond-openio.sgml.gz

Format: postscript
Files: /usr/share/doc/diamond-openio/diamond-openio.ps.gz

Format: text
Files: /usr/share/doc/diamond-openio/diamond-openio.text.gz

Format: HTML
Index: /usr/share/doc/diamond-openio/html/index.html
Files: /usr/share/doc/diamond-openio/html/*.html
