Document: openio-asn1c
Title: Debian openio-asn1c Manual
Author: <insert document author here>
Abstract: This manual describes what openio-asn1c is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/openio-asn1c/openio-asn1c.sgml.gz

Format: postscript
Files: /usr/share/doc/openio-asn1c/openio-asn1c.ps.gz

Format: text
Files: /usr/share/doc/openio-asn1c/openio-asn1c.text.gz

Format: HTML
Index: /usr/share/doc/openio-asn1c/html/index.html
Files: /usr/share/doc/openio-asn1c/html/*.html
