Document: python-socketio2
Title: Debian python-socketio2 Manual
Author: <insert document author here>
Abstract: This manual describes what python-socketio2 is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/python-socketio2/python-socketio2.sgml.gz

Format: postscript
Files: /usr/share/doc/python-socketio2/python-socketio2.ps.gz

Format: text
Files: /usr/share/doc/python-socketio2/python-socketio2.text.gz

Format: HTML
Index: /usr/share/doc/python-socketio2/html/index.html
Files: /usr/share/doc/python-socketio2/html/*.html
