bin/zkCleanup.sh /usr/share/zookeeper/bin/
bin/zkCli.sh /usr/share/zookeeper/bin/
bin/zkServer.sh /usr/share/zookeeper/bin/
debian/conf_example /etc/zookeeper/
debian/zooinspector /usr/bin
build/zookeeper-contrib/zookeeper-contrib-zooinspector/config/* /etc/zookeeper/zooinspector
build/zookeeper-contrib/zookeeper-contrib-zooinspector/icons /usr/share/zookeeper/zooinspector
build/zookeeper-contrib/zookeeper-contrib-zooinspector/zookeeper-zooinspector.jar /usr/share/zookeeper/zooinspector
