Document: python-djangorestframework-jwt
Title: Debian python-djangorestframework-jwt Manual
Author: <insert document author here>
Abstract: This manual describes what python-djangorestframework-jwt is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/python-djangorestframework-jwt/python-djangorestframework-jwt.sgml.gz

Format: postscript
Files: /usr/share/doc/python-djangorestframework-jwt/python-djangorestframework-jwt.ps.gz

Format: text
Files: /usr/share/doc/python-djangorestframework-jwt/python-djangorestframework-jwt.text.gz

Format: HTML
Index: /usr/share/doc/python-djangorestframework-jwt/html/index.html
Files: /usr/share/doc/python-djangorestframework-jwt/html/*.html
