Document: python-django-celery-with-redis
Title: Debian python-django-celery-with-redis Manual
Author: <insert document author here>
Abstract: This manual describes what python-django-celery-with-redis is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/python-django-celery-with-redis/python-django-celery-with-redis.sgml.gz

Format: postscript
Files: /usr/share/doc/python-django-celery-with-redis/python-django-celery-with-redis.ps.gz

Format: text
Files: /usr/share/doc/python-django-celery-with-redis/python-django-celery-with-redis.text.gz

Format: HTML
Index: /usr/share/doc/python-django-celery-with-redis/html/index.html
Files: /usr/share/doc/python-django-celery-with-redis/html/*.html
