Document: puppet-module-openio-diamond
Title: Debian puppet-module-openio-diamond Manual
Author: <insert document author here>
Abstract: This manual describes what puppet-module-openio-diamond is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/puppet-module-openio-diamond/puppet-module-openio-diamond.sgml.gz

Format: postscript
Files: /usr/share/doc/puppet-module-openio-diamond/puppet-module-openio-diamond.ps.gz

Format: text
Files: /usr/share/doc/puppet-module-openio-diamond/puppet-module-openio-diamond.text.gz

Format: HTML
Index: /usr/share/doc/puppet-module-openio-diamond/html/index.html
Files: /usr/share/doc/puppet-module-openio-diamond/html/*.html
