Document: openio-dashboard-backend
Title: Debian openio-dashboard-backend Manual
Author: <insert document author here>
Abstract: This manual describes what openio-dashboard-backend is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/openio-dashboard-backend/openio-dashboard-backend.sgml.gz

Format: postscript
Files: /usr/share/doc/openio-dashboard-backend/openio-dashboard-backend.ps.gz

Format: text
Files: /usr/share/doc/openio-dashboard-backend/openio-dashboard-backend.text.gz

Format: HTML
Index: /usr/share/doc/openio-dashboard-backend/html/index.html
Files: /usr/share/doc/openio-dashboard-backend/html/*.html
