Document: gridadmin-tools
Title: Debian gridadmin-tools Manual
Author: <insert document author here>
Abstract: This manual describes what gridadmin-tools is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/gridadmin-tools/gridadmin-tools.sgml.gz

Format: postscript
Files: /usr/share/doc/gridadmin-tools/gridadmin-tools.ps.gz

Format: text
Files: /usr/share/doc/gridadmin-tools/gridadmin-tools.text.gz

Format: HTML
Index: /usr/share/doc/gridadmin-tools/html/index.html
Files: /usr/share/doc/gridadmin-tools/html/*.html
