Document: openio-gridinit
Title: Debian openio-gridinit Manual
Author: <insert document author here>
Abstract: This manual describes what openio-gridinit is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/openio-gridinit/openio-gridinit.sgml.gz

Format: postscript
Files: /usr/share/doc/openio-gridinit/openio-gridinit.ps.gz

Format: text
Files: /usr/share/doc/openio-gridinit/openio-gridinit.text.gz

Format: HTML
Index: /usr/share/doc/openio-gridinit/html/index.html
Files: /usr/share/doc/openio-gridinit/html/*.html
