#!/bin/sh

INIT_TEMPLATE=${1}

# Get the variables defined in the init template
. ${INIT_TEMPLATE}

SYSTEM_USER=${PROJECT_NAME}
SYSTEM_GROUP=${PROJECT_NAME}

# Find out what should go in After=
SHOULD_START=`cat ${INIT_TEMPLATE} | grep "# Should-Start:" | sed 's/# Should-Start://'`

INIT_FILE=`echo ${INIT_TEMPLATE} | sed 's/.init.in/.init/'`
SERVICE_FILE=`echo ${INIT_TEMPLATE} | sed 's/.init.in/.service/'`

if [ -n "${SHOULD_START}" ] ; then
	AFTER="After="
	for i in ${SHOULD_START} ; do
		AFTER="${AFTER}${i}.service "
	done
fi

if [ -n "$SYSTEMD_DOC" ] ; then
    SYSTEMD_DOC="Documentation=$SYSTEMD_DOC"
fi

########
# init #
########
cp "$INIT_TEMPLATE" "$INIT_FILE"
cat debian/init-script-template >>"$INIT_FILE"

###########
# systemd #
###########
echo "[Unit]
Description=${DESC}
ConditionFileNotEmpty=/etc/${PROJECT_NAME}/${CONFIG}.conf
AssertFileNotEmpty=/etc/swift/account.ring.gz
AssertFileNotEmpty=/etc/swift/container.ring.gz
AssertPathExistsGlob=/etc/swift/object*.ring.gz
$SYSTEMD_DOC
$AFTER
After=network-online.target local-fs.target remote-fs.target 
Wants=network-online.target 

[Service]
User=${SYSTEM_USER}
Group=${SYSTEM_GROUP}
WorkingDirectory=~
CacheDirectory=${PROJECT_NAME}
RuntimeDirectory=${PROJECT_NAME} lock/${PROJECT_NAME}
ExecStart=/usr/bin/${NAME} /etc/${PROJECT_NAME}/${CONFIG}.conf
Restart=on-failure
LimitNOFILE=65535

[Install]
WantedBy=multi-user.target
" >${SERVICE_FILE}

##############################

if [ "$MULTI" ] ; then

SERVICE_FILE=`echo ${INIT_TEMPLATE} | sed 's/.init.in/@.service/'`
SERVICE_NAME=${INIT_TEMPLATE%.init.in}
SERVICE_NAME=${SERVICE_NAME##*/}
SERVICE_NAME=${SERVICE_NAME##*.}

echo "[Unit]
Description=${DESC}
PartOf=${SERVICE_NAME}.service
ReloadPropagatedFrom=${SERVICE_NAME}.service
ConditionFileNotEmpty=/etc/${PROJECT_NAME}/${CONFIG}/%i.conf
AssertFileNotEmpty=/etc/swift/account.ring.gz
AssertFileNotEmpty=/etc/swift/container.ring.gz
AssertPathExistsGlob=/etc/swift/object*.ring.gz
$SYSTEMD_DOC
$AFTER

[Service]
User=${SYSTEM_USER}
Group=${SYSTEM_GROUP}
WorkingDirectory=~
CacheDirectory=${PROJECT_NAME}
RuntimeDirectory=${PROJECT_NAME} lock/${PROJECT_NAME}
ExecStart=/usr/bin/${NAME} /etc/${PROJECT_NAME}/${CONFIG}/%i.conf
Restart=on-failure
LimitNOFILE=65535

[Install]
WantedBy=multi-user.target
" >${SERVICE_FILE}

fi
